const categories = [
  {
    name: "Generative AI",
    categoryId: 108,
    technologyId: 1001,
    categoryUrl: "/certifications/generative-ai-courses/",
    programs: [
      {
        productId: 432,
        productName: "Applied Generative AI Specialization",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/perdue.svgz",
        universityName: "Purdue University",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "16 weeks",
        courseDescription:
          "Master applied generative AI techniques with Purdue University.",
        courseImageUrl: "https://i.ibb.co/BYWJTyV/1.jpg",
      },
      {
        productId: 436,
        productName: "Generative AI for Business Transformation",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/perdue.svgz",
        universityName: "Purdue University",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "16 weeks",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_icons/Megamenu%20logos/Microsoft_Home_Product_40px.svgz",
        courseDescription: "Transform business strategies using generative AI.",
        courseImageUrl: "https://i.ibb.co/FLgFxcRh/images-2.jpg",
      },
      {
        productId: 457,
        productName:
          "Professional Certificate Program in Generative AI and Machine Learning - IITG",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/E_and_ict_University_Megamenu_32px.svgz",
        universityName: "E & ICT Academy, IIT Guwahati",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "11 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/E_ICT_University_Colored_40px.svgz",
        courseDescription: "Advance your AI skills with IIT Guwahati.",
        courseImageUrl: "https://i.ibb.co/F45hXrK2/images-1.jpg",
      },
      {
        productId: 352,
        productName:
          "Professional Certificate Course in Generative AI and Machine Learning",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/IITK_1_32px.svgz",
        universityName: "E & ICT Academy, IIT Kanpur",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "11 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_icons/University_iitk_Colored_40px.svgz",
        courseDescription:
          "Gain expertise in generative AI and machine learning from IIT Kanpur.",
        courseImageUrl: "https://i.ibb.co/svyKhfhJ/images.jpg",
      },
      {
        productId: 160,
        productName: "Post Graduate Program in AI and Machine Learning",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/perdue.svgz",
        universityName: "Purdue University",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "11 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Purdue_HM_40px.svgz",
        courseDescription:
          "Achieve AI expertise with Purdue University’s program.",
        courseImageUrl: "https://i.ibb.co/ycwnhQvT/download-3.jpg",
      },
      {
        productId: 475,
        productName: "Advanced Executive Program In Applied Generative AI",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/IITMPravartakLogo.svgz",
        universityName: "IITM Pravartak",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "4 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_icons/IITMPravartakLogo.svgz",
        courseDescription:
          "Learn advanced applied generative AI with IITM Pravartak.",
        courseImageUrl: "https://i.ibb.co/G4Hmg7Qj/download-2.jpg",
      },
    ],
  },
  {
    name: "AI & Machine Learning",
    categoryId: 33,
    technologyId: 1002,
    categoryUrl: "/ai-and-machine-learning/",
    programs: [
      {
        productId: 352,
        productName:
          "Professional Certificate Course in Generative AI and Machine Learning",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/IITK_1_32px.svgz",
        universityName: "E & ICT Academy, IIT Kanpur",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "11 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_icons/University_iitk_Colored_40px.svgz",
        courseDescription:
          "Gain expertise in Generative AI and Machine Learning from IIT Kanpur.",
        courseImageUrl: "https://i.ibb.co/fd2XYhMk/download.jpg",
      },
      {
        productId: 349,
        productName: "Caltech Post Graduate Program in AI and Machine Learning",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Caltech%20(1).svgz",
        universityName: "Caltech CTME",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "11 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Caltech_HM_40px.svgz",
        courseDescription:
          "Earn a post-graduate certification in AI and Machine Learning from Caltech.",
        courseImageUrl: "https://i.ibb.co/rGQcBNpH/download-1.jpg",
      },
      {
        productId: 457,
        productName:
          "Professional Certificate Program in Generative AI and Machine Learning - IITG",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/E_and_ict_University_Megamenu_32px.svgz",
        universityName: "E & ICT Academy, IIT Guwahati",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "11 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/E_ICT_University_Colored_40px.svgz",
        courseDescription:
          "Advance your skills in AI and Machine Learning with IIT Guwahati.",
        courseImageUrl: "https://i.ibb.co/LdP3xJ4r/download-2.jpg",
      },
      {
        productId: 160,
        productName: "Post Graduate Program in AI and Machine Learning",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/perdue.svgz",
        universityName: "Purdue University",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "11 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Purdue_HM_40px.svgz",
        courseDescription:
          "Achieve AI expertise with Purdue University’s comprehensive program.",
        courseImageUrl: "https://i.ibb.co/k6wz3tqp/download-3.jpg",
      },
      {
        productId: 451,
        productName: "No Code AI and Machine Learning Specialization",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/perdue.svgz",
        universityName: "Purdue University",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "16 weeks",
        courseDescription: "Master AI concepts without programming knowledge.",
        courseImageUrl: "https://i.ibb.co/ZzR41ZXC/download-4.jpg",
      },
      {
        productId: 500,
        productName: "Microsoft AI Engineer Program",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Megamenu%20logos/Microsoft_Megamenu_32px.svgz",
        universityName: "Microsoft",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "6 months",
        courseDescription:
          "Enhance your AI skills with Microsoft’s advanced program.",
        courseImageUrl: "https://i.ibb.co/RrrstYZ/images.jpg",
      },
      {
        productId: 4440,
        productName: "Microsoft Certified Azure AI Engineer Associate: AI 102",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Microsoft-Azure-mm.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        description: "Industry-Aligned Certifications for Career Growth",
        programDurations: "4 weeks",
        courseDescription:
          "Get certified in Azure AI solutions with Microsoft.",
        courseImageUrl: "https://i.ibb.co/6Rj06mDX/images-1.jpg",
      },
      {
        productId: 687,
        productName: "Machine Learning using Python",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Python.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        description: "Industry-Aligned Certifications for Career Growth",
        programDurations: "4 weeks",
        courseDescription: "Learn Python-based machine learning techniques.",
        courseImageUrl: "https://i.ibb.co/PZ6PjFBk/images-2.jpg",
      },
      {
        productId: 117,
        productName: "Artificial Intelligence Engineer",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "11 Months",
        collabrationText: "In Collaboration With IBM_logo",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_icons/IBM_logo%20(1).svgz",
        courseDescription:
          "Become an AI Engineer through this collaborative program with IBM.",
        courseImageUrl: "https://i.ibb.co/BYWJTyV/1.jpg",
      },
    ],
  },

  {
    name: "Project Management",
    categoryId: 1,
    technologyId: 1004,
    categoryUrl: "/project-management/",
    programs: [
      {
        productId: 10,
        productName: "PMP® Certification Training",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/PMI_32px.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "4 weeks",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/p6nCnjmF/download-7.jpg",
      },
      {
        productId: 487,
        productName: "Post Graduate Program in Project Management",
        logo: "https://www.simplilearn.com/ice9/university/Megamenu_60px.svgz",
        universityName: "iHUB Divysampark, IIT Roorkee",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "3 months",
        courseImageUrl: "https://i.ibb.co/21mBb4Zm/download-1.png",
      },
      {
        productId: 2,
        productName: "CAPM® Certification Training",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/PMI_32px.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "4 weeks",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/ZpqCRcVJ/download-1.jpg",
      },
      {
        productId: 116,
        productName: "PMP® Renewal Pack",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "3 weeks",
        collabrationText: "Premier Authorized Training Partner PMI®",
        courseImageUrl: "https://i.ibb.co/Lz22ZJPs/download.png",
      },
      {
        productId: 115,
        productName: "PMP® Plus",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "7 weeks",
        collabrationText: "Premier Authorized Training Partner PMI®",
        courseImageUrl: "https://i.ibb.co/7dT2qb4s/download.jpg",
      },
      {
        productId: 335,
        productName: "PRINCE2® Foundation and Practitioner",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Prince2.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "4 weeks",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/dJHTXW8x/download-2.jpg",
      },
      {
        productId: 1535,
        productName: "PRINCE2® Agile Foundation and Practitioner",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Megamenu%20logos/Prince2_Agile_MM_32px.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "5 weeks",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/Lz22ZJPs/download.png",
      },
    ],
  },
  {
    name: "Cyber Security",
    categoryId: 3,
    technologyId: 1005,
    categoryUrl: "/cyber-security/",
    programs: [
      {
        productId: 489,
        productName: "Executive Certificate Program In Cyber Security",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/IIT_Kanpur_32px.svgz",
        universityName: "IIT Kanpur",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "7 months",
        courseImageUrl: "https://i.ibb.co/BVPqqhmj/download.jpg",
      },
      {
        productId: 279,
        productName: "Advanced Executive Program in Cybersecurity",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/IITb-mm.svgz",
        universityName: "IIIT Bangalore",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "6 Months",
        courseImageUrl: "https://i.ibb.co/MktgH89h/download-1.jpg",
      },
      {
        productId: 127,
        productName: "Cybersecurity Expert Masters Program",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "4 months",
        collabrationText: "Aligned to CompTIA Security+, CEH,  CISSP",
        courseImageUrl: "https://i.ibb.co/wNc9RNHK/download-2.jpg",
      },
      {
        productId: 34,
        productName:
          "CISSP®- Certified Information Systems Security Professional",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/CISSP-mm.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 months",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/LdKHMcWm/download-3.jpg",
      },
      {
        productId: 105,
        productName: "C|EH v13- Certified Ethical Hacker",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/megamenu/EC%20Council.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 months",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/xS75hCBp/images-3.jpg",
      },
      {
        productId: 910,
        productName: "CompTIA Security+ 701",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Megamenu%20logos/Comptia_MM_32px.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 months",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/Xrh6ZR3Y/images-2.jpg",
      },
      {
        productId: 495,
        productName:
          "Professional Certificate Program in Cybersecurity by IITM Pravartak",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/IITMPravartakLogo.svgz",
        universityName: "IITM Pravartak",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "6 months",
        courseImageUrl: "https://i.ibb.co/0yrNvcN2/images-1.jpg",
      },
      {
        productId: 32,
        productName: "CISA®- Certified Information Systems Auditor",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/megamenu/ISACA.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "1 month",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/7tGqkBZq/images.jpg",
      },
      {
        productId: 621,
        productName: "CISM®",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/megamenu/ISACA.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "1 month",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/Xrh6ZR3Y/images-2.jpg",
      },
      {
        productId: 863,
        productName: "CCSP-Certified Cloud Security Professional",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/CCSP-mm.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "3 months",
        courseDescription: "Industry-Aligned Certifications for Career Growth",
        courseImageUrl: "https://i.ibb.co/LdKHMcWm/download-3.jpg",
      },
    ],
  },
  {
    name: "Agile and Scrum",
    categoryId: 9,
    technologyId: 1006,
    categoryUrl: "/agile-and-scrum/",
    programs: [
      {
        productId: 4,
        productName: "Certified ScrumMaster<sup>®</sup> (CSM)",
        url: "/agile-and-scrum/csm-certification-training",
        url_domain: "simplilearn.com",
        programType: "course",
        description: "Industry-Aligned Certifications for Career Growth",
        programDurations: "3 days",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/REA_Scrum_alliance.svgz",
        courseDescription:
          "Comprehensive training for becoming a Certified ScrumMaster.",
        courseImageUrl: "https://i.ibb.co/JwGqRTPL/images.png",
      },
      {
        productId: 766,
        productName:
          "Leading SAFe ® 6 training with SAFe Agilist Certification",
        url: "/agile-and-scrum/safe-agilist-certification-training",
        url_domain: "simplilearn.com",
        programType: "course",
        description: "Industry-Aligned Certifications for Career Growth",
        programDurations: "3 days",
        logoNew:
          "https://www.simplilearn.com/ice9/logos/spctProduct%20page_40px.svgz",
        courseDescription:
          "Learn the principles of SAFe and gain Agilist certification.",
        courseImageUrl: "https://i.ibb.co/j9B8m0xt/images.jpg",
      },
      {
        productId: 5,
        productName: "Certified Scrum Product Owner<sup>®</sup> (CSPO)",
        url: "/agile-and-scrum/cspo-certification-training",
        url_domain: "simplilearn.com",
        programType: "course",
        description: "Industry-Aligned Certifications for Career Growth",
        programDurations: "3 days",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/REA_Scrum_alliance.svgz",
        courseDescription:
          "Master the skills to become an effective Product Owner.",
        courseImageUrl: "https://i.ibb.co/ddsSqN3/download-5.jpg",
      },
      {
        productId: 4529,
        productName:
          "SAFe® 6.0 Release Train Engineer (RTE) Certification Training",
        url: "/agile-and-scrum/safe-rte-certification-training",
        url_domain: "simplilearn.com",
        programType: "course",
        description: "Industry-Aligned Certifications for Career Growth",
        programDurations: "6 days",
        courseDescription:
          "Gain expertise in facilitating Agile Release Trains.",
        courseImageUrl: "https://i.ibb.co/dJ5hhyQd/download-3.jpg",
      },
      {
        productId: 455,
        productName: "Agile Leadership Masters Program",
        url: "/agile-leadership-masters-certification",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "90 days",
        collabrationText: "Accredited with Scrum Alliance - CSM",
        courseDescription:
          "Comprehensive leadership training for Agile environments.",
        courseImageUrl: "https://i.ibb.co/Df1s5QVY/download-2.jpg",
      },
      {
        productId: 474,
        productName: "Advanced Agile Product Ownership Masters",
        url: "/advanced-agile-product-ownership-masters",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "90 days",
        collabrationText: "Accredited with Scrum Alliance - CSPO",
        courseDescription: "Enhance your skills as an Agile Product Owner.",
        courseImageUrl: "https://i.ibb.co/8DH2hMQL/download-1.jpg",
      },
      {
        productId: 919,
        productName: "Professional Scrum Product Owner",
        url: "/professional-scrum-product-owner-pspo-certification-training-course",
        url_domain: "simplilearn.com",
        programType: "course",
        description: "Industry-Aligned Certifications for Career Growth",
        programDurations: "3 days",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Agile_and_Scrum/PSPO_HM_40px.svgz",
        courseDescription:
          "Learn the core competencies of a Scrum Product Owner.",
        courseImageUrl: "https://i.ibb.co/mC2bSWNX/download.jpg",
      },
    ],
  },
  {
    name: "Cloud Computing & DevOps",
    categoryId: 10,
    technologyId: 1007,
    categoryUrl: "/cloud-computing/",
    programs: [
      {
        productId: 453,
        productName:
          "Professional Certificate Program in Cloud Computing and DevOps",
        url: "/cloud-computing-devops-course",
        universityName: "E & ICT Academy, IIT Kanpur",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "8 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_icons/University_iitk_Colored_40px.svgz",
        courseDescription:
          "Comprehensive training in Cloud Computing and DevOps",
        courseImageUrl: "https://i.ibb.co/FLM77GTm/download.jpg",
      },
      {
        productId: 220,
        productName: "Post Graduate Program in Cloud Computing",
        url: "/pgp-cloud-computing-certification-training-course",
        universityName: "Caltech CTME",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "8 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Caltech_HM_40px.svgz",
        courseDescription:
          "Advanced cloud computing concepts with Caltech CTME",
        courseImageUrl: "https://i.ibb.co/HRRx67z/download-1.jpg",
      },
      {
        productId: 216,
        productName: "Post Graduate Program in DevOps",
        url: "/pgp-devops-certification-training-course",
        universityName: "Caltech CTME",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "9 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Caltech_HM_40px.svgz",
        courseDescription: "Expert DevOps training program with Caltech CTME",
        courseImageUrl: "https://i.ibb.co/23sJv4zj/download-2.jpg",
      },
      {
        productId: 101,
        productName: "Cloud Architect Masters Program",
        url: "/cloud-solutions-architect-masters-program-training",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "4 months",
        collabrationText:
          "Cloud Architect accreditation Certification Aligned to Microsoft Azure and AWS",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Cloud_Computing_Homepage/AWS_Azure_HM_40px.svgz",
        courseDescription: "Master skills for cloud architecture roles",
        courseImageUrl: "https://i.ibb.co/bjb0JKtR/download-4.jpg",
      },
      {
        productId: 102,
        productName: "DevOps Engineer Masters Program",
        url: "/devops-engineer-masters-program-certification-training",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "6 months",
        collabrationText: "In collaboration with IBM_logo",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Devops_homepage/IBM_HM_40px.svgz",
        courseDescription:
          "Become a skilled DevOps engineer with real-world projects",
        courseImageUrl: "https://i.ibb.co/bMZpfRKM/images.jpg",
      },
      {
        productId: 183,
        productName: "AWS Cloud Architect Masters Program",
        url: "/aws-cloud-architect-certification-training-course",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "3 months",
        collabrationText: "Certification Aligned to AWS",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Cloud_Computing_Homepage/AWS_HM_40px.svgz",
        courseDescription: "Hands-on training to master AWS cloud solutions",
        courseImageUrl: "https://i.ibb.co/FLM77GTm/download.jpg",
      },
      {
        productId: 184,
        productName: "Azure Cloud Architect Masters Program",
        url: "/azure-cloud-architect-certification-training-course",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "3 months",
        collabrationText: "Powered by Microsoft Cloud Architect Masters",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Cloud_Computing_Homepage/Azure_HM_40px.svgz",
        courseDescription: "Gain expertise in Azure cloud architecture",
        courseImageUrl: "https://i.ibb.co/HRRx67z/download-1.jpg",
      },
      {
        productId: 281,
        productName: "Azure DevOps Solutions Expert Masters Program",
        url: "/azure-devops-solutions-expert-masters-program",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "10 weeks",
        collabrationText: "Powered by Microsoft Cloud Architect Masters",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Cloud_Computing_Homepage/Azure_HM_40px.svgz",
        courseDescription: "Specialized training in Azure DevOps solutions",
        courseImageUrl: "https://i.ibb.co/23sJv4zj/download-2.jpg",
      },
      {
        productId: 670,
        productName: "AWS Solutions Architect",
        url: "/cloud-computing/aws-solution-architect-associate-training",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "3 months",
        description: "Industry-Aligned Certifications for Career Growth",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Cloud_Computing_Homepage/AWS_HM_40px.svgz",
        courseDescription: "Prepare for AWS solutions architect roles",
        courseImageUrl: "https://ibb.co/bjb0JKtR/download-4.jpg",
      },
      {
        productId: 1874,
        productName: "Microsoft Certified DevOps Engineer Expert AZ-400",
        url: "/microsoft-certified-devops-engineer-expert",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "1 month",
        description: "Industry-Aligned Certifications for Career Growth",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Cloud_Computing_Homepage/Azure_HM_40px.svgz",
        courseDescription:
          "Expert DevOps training with Microsoft certification",
        courseImageUrl: "https://i.ibb.co/bMZpfRKM/images.jpg",
      },
      {
        productId: 3895,
        productName: "AWS Cloud Practitioner Essentials",
        url: "/aws-cloud-practitioner-essentials",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 days",
        description: "Industry-Aligned Certifications for Career Growth",
        courseDescription: "Essentials of AWS cloud technology and practices",
        courseImageUrl: "https://i.ibb.co/FLM77GTm/download.jpg",
      },
    ],
  },
  {
    name: "Business and Leadership",
    categoryId: 39,
    technologyId: 1008,
    categoryUrl: "/business-and-leadership-certification-training-courses/",
    programs: [
      {
        productId: 343,
        productName: "Executive Certificate Program in General Management",
        url: "/general-management-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/IIM_Indore-mm.svgz",
        universityName: "Indian Institute of Management Indore",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "6 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/IIM_Indore_HM_40px.svgz",
        courseDescription:
          "Learn core management principles to excel as a leader.",
        courseImageUrl: "https://i.ibb.co/mCWtrh79/images-1.jpg",
      },
      {
        productId: 210,
        productName: "Post Graduate Program in Business Analysis",
        url: "/pgp-business-analysis-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/perdue.svgz",
        universityName: "Purdue University",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "6 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Purdue_HM_40px.svgz",
        courseDescription:
          "Gain expertise in business analysis tools and techniques.",
        courseImageUrl: "https://i.ibb.co/0jXfTmqN/download-2.jpg",
      },
      {
        productId: 84,
        productName: "Business Analyst",
        url: "/business-analyst-certification-training-course",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "11 Months",
        collabrationText: "In collaboration with IBM_logo",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Devops_homepage/IBM_HM_40px.svgz",
        courseDescription:
          "Master advanced business analytics techniques with IBM.",
        courseImageUrl: "https://i.ibb.co/zVk6Y09y/download-1.jpg",
      },
      {
        productId: 291,
        productName:
          "Certified Business Analysis Professional (CBAP\u003Csup\u003E\u00ae\u003C/sup\u003E)",
        url: "/project-management/cbap-preparatory-course-training",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/IIBA_MegaM_32px.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "3 weeks",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/IIBA_HM_40px.svgz",
        courseDescription:
          "Get certified to enhance your business analysis career.",
        courseImageUrl: "https://i.ibb.co/n8CMxpjg/download.png",
      },
      {
        productId: 357,
        productName: "Advanced Certification in UI UX Design",
        url: "/ui-ux-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/IITb-mm.svgz",
        universityName: "IIIT Bangalore",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "5 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/IIITB_HM_40px.svgz",
        courseDescription:
          "Enhance your design skills with expert UI/UX training.",
        courseImageUrl: "https://i.ibb.co/5W9V6TH1/images.jpg",
      },
      {
        productId: 321,
        productName: "Professional Certification in Product Management",
        url: "/product-management-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/SP_Jain.svgz",
        universityName: "SP Jain School of Global Management",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "6 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/SPJain_HM_40.svgz",
        courseDescription:
          "Learn strategic product management techniques for success.",
        courseImageUrl: "https://i.ibb.co/tpvGm2QB/download.jpg",
      },
      {
        productId: 372,
        productName: "Caltech UX/UI Bootcamp",
        url: "/caltech-ui-ux-bootcamp",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Caltech%20(1).svgz",
        universityName: "Caltech CTME",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "5 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Caltech_HM_40px.svgz",
        courseDescription:
          "Build UX/UI expertise with a top-tier Caltech program.",
        courseImageUrl: "https://i.ibb.co/mCWtrh79/images-1.jpg",
      },
      {
        productId: 391,
        productName: "Product Management Professional Program",
        url: "/product-management-training-course-online",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/UC_San_Diego.svgz",
        universityName: "UC San Diego Division of Extended Studies",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "8 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/UC_San_Diego_HM_40px.svgz",
        courseDescription:
          "Master product management skills with expert guidance.",
        courseImageUrl: "https://i.ibb.co/0jXfTmqN/download-2.jpg",
      },
    ],
  },
  {
    name: "Software Development",
    categoryId: 25,
    technologyId: 1009,
    categoryUrl: "/mobile-and-software-development/",
    programs: [
      {
        productId: 267,
        productName: "HTML and CSS Web Design Certification by IIT Kanpur",
        url: "/html-css-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/IIT_Kanpur_32px.svgz",
        universityName: "IIT Kanpur",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "4 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/IIT_Kanpur_40px.svgz",
        courseDescription:
          "Learn the fundamentals of web design using HTML and CSS.",
        courseImageUrl: "https://i.ibb.co/zhqKp5cN/1.jpg",
      },
      {
        productId: 415,
        productName: "Full Stack HTML CSS Developer Masters Program",
        url: "/html-css-full-stack-developer-certification",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "7 months",
        collabrationText: "In collaboration with IBM",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Devops_homepage/IBM_HM_40px.svgz",
        courseDescription:
          "Master front-end and back-end web development using HTML and CSS.",
        courseImageUrl: "https://i.ibb.co/KcHJ2q07/2.jpg",
      },
      {
        productId: 112,
        productName: "Automation Testing with HTML Forms Masters Program",
        url: "/html-testing-masters-program-certification-training-course",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "8 months",
        collabrationText: "In collaboration with IBM",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Devops_homepage/IBM_HM_40px.svgz",
        courseDescription:
          "Learn advanced testing techniques for dynamic HTML forms.",
        courseImageUrl: "https://i.ibb.co/8ghdxgch/3.jpg",
      },
      {
        productId: 433,
        productName: "Full Stack Developer - MERN Stack with HTML and CSS",
        url: "/full-stack-developer-course-mern-html-css-certification-training/",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "6 Months",
        collabrationText: "In collaboration with IBM",
        courseDescription:
          "Become proficient in full stack development using HTML, CSS, and MERN technologies.",
        courseImageUrl: "https://i.ibb.co/Cs6TZg0y/4.jpg",
      },
      {
        productId: 694,
        productName: "Advanced JavaScript with HTML & CSS Certification",
        url: "/mobile-and-software-development/javascript-html-css-training",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Java_32px-mm.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "6 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Java_32px-mm.svgz",
        courseDescription:
          "Master advanced front-end web development with JavaScript, HTML, and CSS.",
        courseImageUrl: "https://i.ibb.co/bjTHHYNS/5.jpg",
      },
      {
        productId: 250,
        productName: "Python for Web Development with HTML & CSS",
        url: "/mobile-and-software-development/python-html-css-training",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Python.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "6 months",
        courseDescription:
          "Learn to develop Python-based web applications using HTML and CSS.",
        courseImageUrl: "https://i.ibb.co/G4Y8p999/6.png",
      },
      {
        productId: 999,
        productName: "Responsive Web Design with HTML5 & CSS3",
        url: "/responsive-web-design-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Responsive_Web.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "5 months",
        courseDescription:
          "Build fully responsive websites using HTML5 and CSS3.",
        courseImageUrl: "https://ibb.co/Q7K8kYzv",
      },
      {
        productId: 1000,
        productName: "UX/UI Design with Advanced HTML & CSS",
        url: "/ux-ui-design-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/UX_UI_Design.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "6 months",
        courseDescription:
          "Learn UX/UI design principles using HTML and CSS for web interfaces.",
        courseImageUrl: "https://i.ibb.co/v6TJ1zmj/1.jpg",
      },
      {
        productId: 1001,
        productName: "Frontend Development with HTML5, CSS, and Bootstrap",
        url: "/frontend-development-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Frontend_Development.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "4 months",
        courseDescription:
          "Master front-end design techniques using HTML5, CSS, and Bootstrap.",
        courseImageUrl: "https://i.ibb.co/XnpWHfy/2.jpg",
      },
      {
        productId: 1002,
        productName: "Advanced Web Animations with HTML, CSS & JavaScript",
        url: "/web-animations-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Web_Animations.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "5 months",
        courseDescription:
          "Learn to create stunning web animations using HTML, CSS, and JavaScript.",
        courseImageUrl: "https://i.ibb.co/wrLq8nTc/3.jpg",
      },
      {
        productId: 1003,
        productName: "Interactive Websites with HTML, CSS & jQuery",
        url: "/interactive-websites-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Interactive_Web.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "6 months",
        courseDescription:
          "Develop interactive websites using HTML, CSS, and jQuery.",
        courseImageUrl: "https://i.ibb.co/JRf4WCTv/4.jpg",
      },
      {
        productId: 1004,
        productName: "Web Development for Beginners with HTML & CSS",
        url: "/web-development-beginners-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Web_Development_Beginners.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "3 months",
        courseDescription:
          "Get started with web development using HTML and CSS.",
        courseImageUrl: "https://i.ibb.co/d02kGC82/5.jpg",
      },
    ],
  },
  {
    name: "Product and Design",
    categoryId: 163,
    technologyId: 1010,
    categoryUrl: "/product-and-design/",
    programs: [
      {
        productId: 357,
        productName: "Advanced Certification in UI UX Design",
        url: "/ui-ux-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/IITb-mm.svgz",
        universityName: "IIIT Bangalore",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "5 months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/IIITB_HM_40px.svgz",
        courseDescription:
          "Learn advanced UI/UX skills with expert instructors.",
        courseImageUrl: "https://i.ibb.co/wZB8yrZ1/download.jpg",
      },
      {
        productId: 321,
        productName: "Professional Certification in Product Management",
        url: "/product-management-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/SP_Jain.svgz",
        universityName: "SP Jain School of Global Management",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "6 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/SPJain_HM_40.svgz",
        courseDescription:
          "Master product management techniques and strategies.",
        courseImageUrl: "https://i.ibb.co/h14y24NJ/download-1.jpg",
      },
      {
        productId: 372,
        productName: "Caltech UX/UI Bootcamp",
        url: "/caltech-ui-ux-bootcamp",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Caltech%20(1).svgz",
        universityName: "Caltech CTME",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "5 months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Caltech_HM_40px.svgz",
        courseDescription: "Get hands-on UX/UI skills from Caltech experts.",
        courseImageUrl: "https://i.ibb.co/4wHxjF9y/download-2.jpg",
      },
      {
        productId: 391,
        productName: "Product Management Professional Program",
        url: "/product-management-training-course-online",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/UC_San_Diego.svgz",
        universityName: "UC San Diego Division of Extended Studies",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "8 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/UC_San_Diego_HM_40px.svgz",
        courseDescription:
          "Become a product management leader with UC San Diego.",
        courseImageUrl: "https://i.ibb.co/F4fFDcPZ/download-3.jpg",
      },
      {
        productId: 400,
        productName: "Comprehensive Design Thinking Bootcamp",
        url: "/design-thinking-bootcamp",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Digital.svgz",
        universityName: "Simplilearn",
        url_domain: "simplilearn.com",
        programType: "bootcamp",
        programDurations: "4 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Simplilearn.svgz",
        courseDescription:
          "Gain expertise in design thinking and problem-solving.",
        courseImageUrl: "https://i.ibb.co/0yPXvNSD/images.jpg",
      },
    ],
  },
  {
    name: "IT Service and Architecture",
    categoryId: 2,
    technologyId: 1011,
    categoryUrl: "/it-service-management/",
    programs: [
      {
        productId: 1176,
        productName: "ITIL<sup>®</sup> 4 Foundation",
        url: "/it-service-management/itil-foundation-training",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 weeks",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/ITIL-Axalos-mm.svgz",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/ITIL-Axalos-mm.svgz",
        courseDescription:
          "Comprehensive foundation training for ITIL 4 certification.",
        courseImageUrl: "https://i.ibb.co/21XHLfgZ/download-4.jpg",
      },
      {
        productId: 184,
        productName:
          "TOGAF® Enterprise Architecture Foundation Training Course",
        url: "/it-service-management/togaf-certification-program-training",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 weeks",
        logo: "https://www.simplilearn.com/ice9/Togaf/TogafMegamenu.svgz",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/IT_Service_and_Architecture_homepage/Open_AI_Pra_HM_40px.svgz",
        courseDescription:
          "Learn enterprise architecture concepts with TOGAF certification.",
        courseImageUrl: "https://i.ibb.co/qMd2Cnc0/imags.jpg",
      },
      {
        productId: 206,
        productName: "ITIL<sup>®</sup> Managing Professional (MP)",
        url: "/itil-managing-professional-training-course",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "8 weeks",
        collabrationText: "Accredited by Axelos-ITIL",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/ITIL-Axalos-mm.svgz",
        courseDescription:
          "Advance your ITIL skills with Managing Professional certification.",
        courseImageUrl: "https://i.ibb.co/tM3m2rG2/images.png",
      },
      {
        productId: 1480,
        productName: "ITIL® 4 Specialist: Create, Deliver and Support",
        url: "/itil-specialist-certification-training",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 weeks",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/ITIL-Axalos-mm.svgz",
        courseDescription:
          "Master IT service delivery with ITIL 4 Specialist certification.",
        courseImageUrl: "https://i.ibb.co/rfmGVLjP/images-1.jpg",
      },
      {
        productId: 1481,
        productName: "ITIL® 4 Strategist: Direct, Plan, and Improve",
        url: "/itil-strategist-certification-training-course",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 weeks",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/ITIL-Axalos-mm.svgz",
        courseDescription:
          "Develop strategic IT skills with ITIL 4 Strategist training.",
        courseImageUrl: "https://i.ibb.co/wVqhX2T/images-2.jpg",
      },
      {
        productId: 1499,
        productName: "ITIL® 4 Specialist: High Velocity IT",
        url: "/itil-specialist-high-velocity-it-course",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 weeks",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/ITIL-Axalos-mm.svgz",
        courseDescription:
          "Learn high-velocity IT practices with ITIL 4 certification.",
        courseImageUrl: "https://i.ibb.co/21XHLfgZ/download-4.jpg",
      },
      {
        productId: 1500,
        productName: "ITIL® 4 Specialist: Drive Stakeholder Value",
        url: "/itil-specialist-drive-stakeholder-value-certification-course",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 weeks",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/ITIL-Axalos-mm.svgz",
        courseDescription:
          "Enhance stakeholder management skills with ITIL 4 certification.",
        courseImageUrl: "https://i.bb.co/qMd2Cnc0/images.jpg",
      },
    ],
  },
  {
    name: "Quality Management",
    categoryId: 4,
    technologyId: 1012,
    categoryUrl: "/quality-management/",
    programs: [
      {
        productId: 244,
        productName: "Certified Lean Six Sigma Green Belt",
        url: "/quality-management/lean-six-sigma-green-belt-training",
        logo: "https://www.simplilearn.com/ice9/LOGO%20/IASSC_Green48px.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "6 weeks",
        logoNew:
          "https://www.simplilearn.com/ice9/LOGO%20/IASSC_Green_40px.svgz",
        courseDescription:
          "Comprehensive training in Lean Six Sigma methodologies.",
        courseImageUrl: "https://i.ibb.co/Txnswpwg/images-1.jpg",
      },
      {
        productId: 42,
        productName: "Certified Lean Six Sigma Black Belt",
        url: "/quality-management/lean-six-sigma-black-belt-training",
        logo: "https://www.simplilearn.com/ice9/LOGO%20/IASSC_Black48px.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "6 weeks",
        logoNew:
          "https://www.simplilearn.com/ice9/LOGO%20/IASSC_Black40px.svgz",
        courseDescription: "Advanced mastery of Lean Six Sigma practices.",
        courseImageUrl: "https://i.ibb.co/21YVJNV3/images.png",
      },
      {
        productId: 242,
        productName: "Professional Certificate Program in Lean Six Sigma",
        url: "/pgp-lean-six-sigma-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/UMass_Amherst.svgz",
        universityName: "University of Massachusetts Amherst",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "12 weeks",
        logoNew: "https://www.simplilearn.com/ice9/new-home/Umass.svgz",
        courseDescription: "Professional certification from UMass Amherst.",
        courseImageUrl: "https://i.ibb.co/M56frZhF/download-1.png",
      },
      {
        productId: 56,
        productName: "Lean Six Sigma Expert",
        url: "/lean-six-sigma-expert-masters-program",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "10 weeks",
        collabrationText: "Accredited By IASSC",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/IASSC_MegaM_32px.svgz",
        courseDescription:
          "Expert-level training in Lean Six Sigma strategies.",
        courseImageUrl: "https://i.ibb.co/nsF7sbmh/download-1.jpg",
      },
      {
        productId: 999,
        productName: "Lean Six Sigma Basics",
        url: "/lean-six-sigma-basics-course",
        logo: "https://www.simplilearn.com/ice9/LOGO%20/Basic_Lean_Sigma.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "4 weeks",
        logoNew:
          "https://www.simplilearn.com/ice9/LOGO%20/Basic_Lean_Sigma_32px.svgz",
        courseDescription: "Introduction to Lean Six Sigma fundamentals.",
        courseImageUrl: "https://i.ibb.co/Tqg5zXqS/download.png",
      },
    ],
  },
  {
    name: "Digital Marketing",
    categoryId: 18,
    technologyId: 1013,
    categoryUrl: "/digital-marketing/",
    programs: [
      {
        productId: 430,
        productName: "Professional Certification in Digital Marketing",
        url: "/professional-digital-marketing-program",
        logo: "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/SP_Jain.svgz",
        universityName: "SP Jain School of Global Management",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "8 Months",
        courseDescription:
          "Comprehensive certification in digital marketing strategies and tools.",
        courseImageUrl: "https://i.ibb.co/rR4hQJPS/download.jpg",
      },
      {
        productId: 244,
        productName: "Post Graduate Program in Digital Marketing",
        url: "/advanced-digital-marketing-certification-training-course",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/perdue.svgz",
        universityName: "Purdue University",
        url_domain: "simplilearn.com",
        programType: "university",
        programDurations: "8 Months",
        logoNew:
          "https://www.simplilearn.com/ice9/new-logo-mix/Purdue_HM_40px.svgz",
        courseDescription:
          "Advanced program for mastering digital marketing skills.",
        courseImageUrl: "https://i.ibb.co/gFvqvs7X/download-1.jpg",
      },
      {
        productId: 23,
        productName: "Digital Marketing Specialist",
        url: "/master-in-digital-marketing",
        logo: "http://simplilearn.com/ice9/accreditation_icons/Masters_program_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "bundle",
        programDurations: "8 Months",
        collabrationText: "Official Partner Meta",
        logoNew:
          "https://www.simplilearn.com/ice9/accreditation_images/Digital%20Business%20Homepage/Meta_HM_40.svgz",
        courseDescription:
          "Master's level program to become a digital marketing expert.",
        courseImageUrl: "https://i.ibb.co/15dr56s/download-2.jpg",
      },
      {
        productId: 260,
        productName: "Search Engine Optimization (SEO) Course",
        url: "/digital-marketing/search-engine-optimization-seo-certification-training",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Simplilearn_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "2 weeks",
        description: "Industry-Aligned Certifications for Career Growth",
        courseDescription:
          "Focused training for mastering search engine optimization.",
        courseImageUrl: "https://i.ibb.co/gM4jHBVn/download-3.jpg",
      },
      {
        productId: 999,
        productName: "Social Media Marketing Course",
        url: "/digital-marketing/social-media-marketing-certification-training",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Simplilearn_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "4 weeks",
        courseDescription:
          "Learn the best strategies for social media marketing.",
        courseImageUrl: "https://i.ibb.co/dJ0Y6CpD/download-4.jpg",
      },
      {
        productId: 1000,
        productName: "Content Marketing Specialist Program",
        url: "/digital-marketing/content-marketing-specialist-certification-training",
        logo: "https://www.simplilearn.com/ice9/accreditation_icons/Simplilearn_logo.svgz",
        url_domain: "simplilearn.com",
        programType: "course",
        programDurations: "6 weeks",
        courseDescription:
          "Specialized course on content marketing strategies.",
        courseImageUrl: "https://i.ibb.co/1tbzGpxs/images.jpg",
      },
    ],
  },
];

const partnerData = [
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/PMI_48px.svgz",
    name: "PMI Certifications",
    displayName: "PMI",
    seo_url: "/certifications/pmi-certifications/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_icons/megamenu/REA_40px.svgz",
    name: "Scrum Alliance Certifications",
    displayName: "Scrum Alliance",
    seo_url: "/certifications/scrum-alliance-certifications/",
  },
  {
    image_url: "https://www.simplilearn.com/ice9/logos/goldspct_48px%20.svgz",
    name: "Scaled Agile Certifications",
    displayName: "Scaled Agile",
    seo_url: "/certifications/scaled-agile-certifications/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Category_page_partner_logo/ISACA_CP_48px.svgz",
    name: "ISACA Certifications",
    displayName: "ISACA",
    seo_url: "/certifications/isaca-certifications/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/Comtia_48px.svgz",
    name: "CompTIA certifications",
    displayName: "CompTIA",
    seo_url: "/certifications/comptia-certifications/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Category_page_partner_logo/AWS_CP_48px.svgz",
    name: "AWS Courses",
    displayName: "AWS Courses",
    seo_url: "/certifications/aws-courses/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Google_Cloud-mm.svgz",
    name: "Google Cloud Courses",
    displayName: "Google Cloud",
    seo_url: "/certifications/google-cloud-courses/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/ProgramPage/Category%20product_48px.svgz",
    name: "PeopleCert Certifications",
    displayName: "PeopleCert",
    seo_url: "/certifications/peoplecert-certifications/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Category_page_partner_logo/EC_CP_48px.svgz",
    name: "ECCouncil Certifications",
    displayName: "ECCouncil",
    seo_url: "/certifications/eccouncil-certifications/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/itil-axelos.png",
    name: "AXELOS Certifications",
    displayName: "AXELOS",
    seo_url: "/certifications/axelos-courses/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Devops_homepage/IBM_HM_40px.svgz",
    name: "IBM Courses",
    displayName: "IBM Courses",
    seo_url: "/certifications/ibm-courses/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Megamenu%20Logos/Microsoft-Azure-mm.svgz",
    name: "Microsoft",
    displayName: "Microsoft",
    seo_url: "/certifications/microsoft-certification",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/accreditation_images/Category_Logos/CISSP_CCSP_48_CP.svgz",
    name: "ISC2 Certifications",
    displayName: "ISC2",
    seo_url: "/certifications/isc2-certifications/",
  },
];

const Industries = [
  {
    image_url:
      "https://www.simplilearn.com/ice9/university/IITK-University-Logo-Colored-48px.svgz",
    name: "IIT Kanpur Courses",
    displayName: "IIT-Kanpur",
    seo_url: "/certifications/iit-kanpur-courses/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/university/University_Logo_Colored_48px.svgz",
    name: "E & ICT Academy, IIT Guwahati",
    displayName: "E & ICT Academy, IIT Guwahati",
    seo_url: "/certifications/iit-guwahati-courses",
  },
  {
    image_url: "https://www.simplilearn.com/ice9/university/IIITB_CP_48px.svgz",
    name: "IIIT Bangalore Courses",
    displayName: "IIIT-Bangalore",
    seo_url: "/certifications/iiit-bangalore-courses/",
  },
  {
    image_url: "https://www.simplilearn.com/ice9/university/Caltechctme.svgz",
    name: "Caltech CTME",
    displayName: "Caltech CTME",
    seo_url: "/certifications/caltech-courses",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/university/Purdue_CategoryPage_48px.svgz",
    name: "Purdue University",
    displayName: "Purdue University",
    seo_url: "/certifications/purdue-courses",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/university/Umass_48_mega_menu.svgz",
    name: "UMass Courses",
    displayName: "UMass",
    seo_url: "/certifications/umass-courses/",
  },
  {
    image_url: "https://www.simplilearn.com/ice9/university/SP_Jain_48px.svgz",
    name: "SP Jain School of Global Management",
    displayName: "SP Jain School of Global Management",
    seo_url: "/certifications/sp-jain-courses",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/university/university-logo-coloured-n.svgz",
    name: "IIT Roorkee Courses",
    displayName: "IIT Roorkee Courses",
    seo_url: "/certifications/iit-roorkee-courses/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/university/University_Logo_Header_coloured.svgz",
    name: "IIT Madras Courses",
    displayName: "IIT Madras Certification Courses",
    seo_url: "/certifications/iit-madras-courses/",
  },
  {
    image_url:
      "https://www.simplilearn.com/ice9/university/University_iitk_48px.svgz",
    name: "E&ICT Academy, IIT Kanpur",
    displayName: "E&ICT Academy, IIT Kanpur",
    seo_url: "/certifications/e-ict-kanpur-courses/",
  },
];

module.exports = { categories, partnerData, Industries };
